Update admin.yml

diff --git a/.github/workflows/admin.yml b/.github/workflows/admin.yml
--- a/.github/workflows/admin.yml
+++ b/.github/workflows/admin.yml
@@ -121,11 +121,33 @@ jobs:
           sudo apt-get update
           sudo apt-get install -y zip
 
-      - name: Create Artifact Folder Structure
+      - name: Commit Artifact History
+        shell: bash
         run: |
-          mkdir -p artifacts/AdminAPI/New
-          mkdir -p artifacts/AdminAPI/Old1
-          mkdir -p artifacts/AdminAPI/Old2
+          git config user.name "github-actions"
+          git config user.email "github-actions@github.com"
+          git checkout ${GITHUB_REF_NAME}
+          git add artifacts
+          if git diff --cached --quiet; then
+             echo "No artifact changes."
+             exit 0
+          fi
+          TIMESTAMP=$(TZ=Asia/Kolkata date +"%Y-%m-%d %H:%M:%S IST")
+          git commit -m "AdminAPI Artifact | Sprint ${SPRINT} | Patch ${PATCH} | ${TIMESTAMP}"
+          for i in 1 2 3
+          do
+            if git pull --rebase origin ${GITHUB_REF_NAME} && \
+              git push origin ${GITHUB_REF_NAME}; then
+           echo "Push Successful"
+           exit 0
+           fi
+
+          echo "Retry $i..."
+          sleep 2
+          done
+
+          echo "Push failed after 3 attempts."
+          exit 1
 
       - name: Rotate Existing Artifacts
         shell: bash
@@ -167,45 +189,21 @@ jobs:
             artifacts/AdminAPI/New/${ARTIFACT_NAME} \
             publish/AdminAPI
 
-      - name: Commit Artifact History
+      - name: Create Latest Artifact
         shell: bash
         run: |
+           TIMESTAMP=$(TZ=Asia/Kolkata date +"%Y%m%d_%H%M%S")
+           ARTIFACT_NAME="Admin_Sprint${SPRINT}_Patch${PATCH}_${TIMESTAMP}.zip"
 
-          git config user.name "github-actions"
-          git config user.email "github-actions@github.com"
+           echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_ENV
 
-          git checkout ${GITHUB_REF_NAME}
-
-          git add artifacts
-
-          if git diff --cached --quiet; then
-            echo "No artifact changes."
-            exit 0
-          fi
-
-          TIMESTAMP=$(TZ=Asia/Kolkata date +"%Y-%m-%d %H:%M:%S IST")
-
-          git commit -m "AdminAPI Artifact | Sprint ${SPRINT} | Patch ${PATCH} | ${TIMESTAMP}"
-
-          for i in 1 2 3
-          do
-            if git pull --rebase origin ${GITHUB_REF_NAME} && \
-               git push origin ${GITHUB_REF_NAME}; then
-              echo "Push Successful"
-              exit 0
-            fi
-
-            echo "Retry $i..."
-            sleep 2
-          done
-
-          echo "Push failed after 3 attempts."
-          exit 1
-
+           zip -r \
+             artifacts/AdminAPI/New/${ARTIFACT_NAME} \
+             publish/AdminAPI
       - name: Upload GitHub Artifact
         uses: actions/upload-artifact@v4
         with:
-          name: ${{ env.ARTIFACT_NAME }}
-          path: artifacts/AdminAPI/New/${{ env.ARTIFACT_NAME }}
-          retention-days: 30
-          if-no-files-found: error
+           name: AdminAPI-Latest
+           path: artifacts/AdminAPI/New/${{ env.ARTIFACT_NAME }}
+           retention-days: 30
+           if-no-files-found: error
